title: OuEstCharlie Blog
description: Open, AI-native photo management — built on open standards and privacy
baseurl: "/ouestcharlie"
url: "https://antoinehue.github.io"

theme: minima

author:
  name: OuEstCharlie

permalink: /:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag
